### ISSUE TITLE
sound and ui don't work on big screens unless you resize browser window to hide editing area first

### ISSUE THREAD

**Issue by caryoscelus** [grame-cncm/faustide#107]
tried different browsers (firefox/librewolf/chromium), none work when launching normally (this is a regression, week ago it worked fine). however, i tried on mobile and it works fine (except small screen inconveniences). then i decided to try emulating mobile screen size on librewolf (using ctrl-shift-m) and after that it worked, even if returned to normal later

in particular, buttons don't work; ctrl+r doesn't work, but seems to reload the page instead (code is not preserved); it doesn't play sound, but actually also doesn't even ask for mic/midi permission

**Comment by Fr0stbyteR** [comment]
@sletz I saw that bootstrap has been upgraded to a major version that might break the UI

**Comment by sletz** [comment]
@Fr0stbyteR  How that !? well I've just merge a dependbot PR. Woking normally here (after a small hiccup yesterday do to missing regeneration)

**Comment by caryoscelus** [comment]
i should probably mention that i'm using site version (https://faustide.grame.fr/)

**Comment by sletz** [comment]
@Fr0stbyteR should I go back to bootstrap 4.6.9 ?

**Comment by caryoscelus** [comment]
seems to work fine now. i don't think anything changed on my side

**Comment by sletz** [comment]
Nothing changed on my side for now... ((-;

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faustide/commit/abd6ad61989588426ae35d31061316bdc8f93101;
