### ISSUE TITLE
missing js in dist mode

### ISSUE THREAD

**Issue by dfober** [grame-cncm/faustide#14]
the following files 
~~~~~~~~
js/c9bc977960e6a6f7c7bf.js.map 
js/c9bc977960e6a6f7c7bf.js 
js/59f5246d165b91115b41.js 
js/eaadba58d4ed3f96894e.js.map 
js/eaadba58d4ed3f96894e.js 
js/59f5246d165b91115b41.js.map 
~~~~~~~~
are missing when running `npm run dist` while not with `npm run build`
Thus the resulting web site doesn't work in `dist` mode.

**Comment by sletz** [comment]
Strange, because I was using "npm run build" as described in the README...

**Comment by Fr0stbyteR** [comment]
Just a reminder, if you are using `npm run dist` for minified js, make sure you changed `index.js` to `index.min.js` in `index.html` where it loads the script, and maybe need more cleanups...

**Comment by dfober** [comment]
ok ! it works with the change.
It's a dangerous trap. We should find a way to change that automatically.
Would it be in webpack possibilities?

**Comment by sletz** [comment]
I guess "dist" produces more efficient code (like minified stuff and so on?) 
@Fr0stbyteR what is the recommend way to do then ?

**Comment by Fr0stbyteR** [comment]
`dist` is a kinda more efficient but as `faust2webaudio` is already minified, I don't think there would be huge difference, plus, dist is really slow so I usually do the build.
It is possible to dynamically choose which index.html to product using webpack with `CopyWebpackPlugin`, which copies files automatically, possibly with `CleanWebpackPlugin` which do the cleanups.

**Comment by Fr0stbyteR** [comment]
I'll try to do a PR for this in the week

**Comment by Fr0stbyteR** [comment]
https://github.com/grame-cncm/faustide/pull/15
