### ISSUE TITLE
Add the additional libraries when exporting DSP

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faustide#17]
In the online faustide, I can include external .lib files and they are included when I run the main .dsp file. But when I want to export the project to vst (or any other destination), the (external) .lib files are not found.

**Comment by Fr0stbyteR** [comment]
I think it is because the `expandCode()` is no longer used, Is there a way to upload multiple files to the server using AJAX+FormData?

**Comment by sletz** [comment]
external .lib files are now sent on the server when compiling.
