### ISSUE TITLE
Cannot use Web MIDI keyboard

### ISSUE THREAD

**Issue by jadomingo** [grame-cncm/faustide#2]
Web MIDI is deprecated for insecure origins, please update it

https://www.chromestatus.com/feature/5138066234671104

**Comment by sletz** [comment]
The editor runs on an https server. Is that not enough?

**Comment by jadomingo** [comment]
I'm just echoing the error Chrome throws out. I don't really know what's going on under the hood.

**Comment by sletz** [comment]
Which exact address are you using ?

**Comment by jadomingo** [comment]
https://faust.grame.fr/tools/editor/

**Comment by sletz** [comment]
I understand the browser will ask for the user permission at that point. So AFAICS nothing special has to be done.

**Comment by jadomingo** [comment]
Alright. How do I make the MIDI keyboard pop up? I followed the start-up guide and turned MIDI polyphonic mode on but nothing pops up.

**Comment by sletz** [comment]
1) Try this polyphonic aware instrument ( 
https://faust.grame.fr/editor/?buffer=256&poly=on&nvoices=64&code=https://raw.githubusercontent.com/grame-cncm/faust/master-dev/tests/architecture-tests/organ.dsp, compile/run
2) set MIDI/polyphony mode to ON  (left-bottom)
3) Playing notes should work
