### ISSUE TITLE
wrong SampleRate in Faust Online IDE

### ISSUE THREAD

**Issue by sennert** [grame-cncm/faustide#25]
Hey! 
I'm sorry, I know this is for the Online Editor, not the Online IDE, but I could not find a place to report the Bug that I just found:

In the IDE when I record the Audio Output Stream and save is as a recording (Wav) it gets saved with a Samplerate of 44100khz (regardless of the Samplerate of my System). But my SystemSamplerate was 48000kHz while Recording. The Recorded File is pitched down (and its Metadata says 44100kHz Samplerate).

Maybe somebody can guide me where to address the right people for this. thank you!

**Comment by sletz** [comment]
With which browser and platform ?

**Comment by sennert** [comment]
Chrome Version 83.0.4103.116
Mac OS X 10.14.6
MacBook Pro (15-inch, 2018)

**Comment by sennert** [comment]
when I set the SystemAudio to 44100 everything works fine as expected

**Comment by Fr0stbyteR** [comment]
#26 should fix the bug.

**Comment by sletz** [comment]
@sennert The IDE site has been re-deployed.

**Comment by sennert** [comment]
amazing! Still recording with 44100 regardless of SystemAudiorate, but now the Pitch is correct. Thank you for the quick fix 👍

**Comment by Fr0stbyteR** [comment]
> amazing! Still recording with 44100 regardless of SystemAudiorate, but now the Pitch is correct. Thank you for the quick fix 👍

Hi @sennert , Now the recording sample rate will adapt to the browser (when open the page it initialize the sample rate according to the system), and is the same as shown on the left panel. If you refresh the page it still says 44100 when the system is at 48000?

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faustide/commit/48604381e4af709a4029bc6a3ae08b33cfbd763d.

**Comment by sennert** [comment]
@Fr0stbyteR Yes, that works for me now (tested with SystemRate 44.1/48/88.2/96)
Thank you!
