### ISSUE TITLE
Problem with long Filenames and fixed Width of Left Panel Filebrowser

### ISSUE THREAD

**Issue by sennert** [grame-cncm/faustide#27]
Hello again,

Just a minor Issue, but I've imported a prewritten .dsp file via Drag and Drop into the Online IDE. The Filename has 24 characters without ".dsp". 
I would like to rename the file or delete it, but I cannot access the rename/delete button because the end of the filename is hidden. I tried to resize the Window and Fontsize, etc... but I'm not able to get to the buttons.

Maybe you can make the width of the left Panel resizable like it is possible for the right Panel. Or keep a fixed width but overlay the rename/delete Button on top of the Filename.

Thank you very much! 
cheers,
steffen

Chrome Version 83.0.4103.116 
Mac OS 10.14.6

**Comment by sennert** [comment]
tried to find a solution in the Code but I don't know so much about programming for web than a bit of HMLT (and new github), sorry. 
I guess it's not done by just adding another div container with id="left-resizable" class="resizable resizable-right" after line 31 in Index.html ?

**Comment by Fr0stbyteR** [comment]
FIxed in the PR #28

**Comment by sletz** [comment]
Should be fixed in  https://github.com/grame-cncm/faustide/commit/92a096a00617dd66b78683911909fed976e9247a
Can you test and report? Thanks.

**Comment by sennert** [comment]
Love it! That fixed the problem for me :)
