### ISSUE TITLE
Links to documentation (ctrl-d) broken

### ISSUE THREAD

**Issue by akalmbach** [grame-cncm/faustide#33]
On https://fausteditor.grame.fr/ when you write code and press the docs button on the left menu or Ctrl-D the IDE opens a new tab to take you to some documentation. Currently this takes you to pages under https://faustlibdoc.grame.fr/ however the docs seemed to have moved to https://faustlibraries.grame.fr/.

Eg. Highlighting `ba.pulsen` in the editor and pressing Ctrl-D opens https://faustlibdoc.grame.fr/#bapulsen which no longer exists. Correct looking documentation is at https://faustlibraries.grame.fr/libs/basics/#bapulsen.

Unfortunately google doesn't reliably come up with the right page in the top couple links when I search for faust components, so for a new user like me this would be a super useful fix!

**Comment by Dustoe** [comment]
The problem seems to have changed but is still present. Ctrl-D now redirects to https://faust.grame.fr/doc/libraries/ which gets to a 404 error from the website.

**Comment by sletz** [comment]
Fixed.
