### ISSUE TITLE
Accidentally run a intensive patch = cannot open IDE again without clearing local storage

### ISSUE THREAD

**Issue by dxinteractive** [grame-cncm/faustide#40]
First up, thanks so much for building such a great IDE! I've spent days using it now and it's so fully featured and easy to use.

The one issue I've hit a couple of times is that if you accidentally make a typo that results in a patch that's too heavy to run, then the tab will hang and crash. That's fine, but when you try to go back to the IDE, it automatically loads the last patch AND automatically attempts to run it again, which leads to the tab immediately hanging, so you can't correct the mistake and can really only get back to the IDE using a new private browsing tab or clearing local storage, both of which mean you lose your work.

e.g. For a trivial example I had something like a `process = par(i,99,os.oscsin(i * 0.1)) :> _,_`, which is quite heavy already. I accidentally typed an extra 9 (so `...,999,...`) and now the IDE always crashes.

**Comment by Fr0stbyteR** [comment]
I made a pull request related to this issue, after it being merged and deployed, you can use `realtime_compile=0` url parameter to forse disable the auto-compilation of the diagram when the IDE started, for example `https://faustide.grame.fr/?realtime_compile=0`. 
up to @sletz to do the merge ;)

**Comment by sletz** [comment]
Pull request https://github.com/grame-cncm/faustide/pull/41 merge. @dxinteractive can you test?

**Comment by sletz** [comment]
@rmichon BTW, this should help in your use-case also.

**Comment by dxinteractive** [comment]
@Fr0stbyteR @sletz perfect, after a bit of a forceful nudge to update my browser cache, that has worked wonderfully. Thanks for such a swift response.
