### ISSUE TITLE
Uncaught TypeError: r(...).readFile is not a function

### ISSUE THREAD

**Issue by ojack** [grame-cncm/faustide#49]
I get this error when trying to run locally, and the IDE does not fully load. It seems like it is coming from faust2webaudio (see image for stack trace). Let me know if there is a way to avoid. I am using Chrome on Ubuntu 18.04. 
![Screenshot from 2021-11-23 13-52-22](https://user-images.githubusercontent.com/4909769/143028605-0f0f712c-cf97-4336-8251-53e8de9c80ea.png)
.

**Comment by sletz** [comment]
I've just regenerated here: https://github.com/grame-cncm/faustide/commits/master. Can can pull the latest version and try again?

**Comment by ojack** [comment]
It works! thank you
