### ISSUE TITLE
GUI controls stop working after a few seconds

### ISSUE THREAD

**Issue by davigega** [grame-cncm/faustide#50]
Hello!
I'm having some issues working with the IDE:
No matter what I program, the GUI elements stop working after a few seconds.
I am talking about very simple programs such as:
```faust
import("stdfaust.lib");

volume = vslider("Volume", 0, 0, 1, 0.01): si.smoo;
sig = os.osci(300);

process = sig*volume;
```
The DSP runs as expected, and it doesn't stop. After a few seconds I just cannot interact with the slider any more. In this example the amplitude value would hang to "the last registered position" of the slider.
No matter which DSP engine I am using (SignalProcessor or AudioWorklet) and which browser I am using (Firefox, Chrome, Chromium)

I am experiencing the same problem with a local installation, which makes me guess that the problem might be related to the browser, but I wouldn't know how to further debug the Issue all by myself.

I am working on a machine running Debian GNU/Linux bookworm/sid
Firefox 91.4.0esr (64-bit)
Chrome Version 96.0.4664.110 (Official Build) (64-bit)

Congratulation for your amazing work! Faust is a real revolution

**Comment by sletz** [comment]
Do you see any error message in the JS console?

**Comment by davigega** [comment]
Just a warning:
```
WARNING : cannot generate helper JS file, outpath is incorrect : "/dev/null"
```
and sometimes from Firefox :
```
asm.js type error: Disabled because no suitable wasm compiler is available
```

**Comment by sletz** [comment]
Working here on macOS, no nothing I can do more on my side. You can possibly use the Faust Slack channel or Discord "The Audio Programmer" to get more help from Debian users ?

**Comment by davigega** [comment]
Since I am not experiencing this problem when browsers run in _Safe Mode_  I realised that the only browser extension that I have installed in both Firefox and Chrome is **ExpressVPN**. If I disabled it everything works as expected.
It seems that this extension runs a loop in the background, when "Not Connected", which interferes with some `changeValue` function of the UIElements.
I have no solution but maybe is safe enough to highlight this Issue in the `README` (as suggested by @sletz )

**Comment by sletz** [comment]
PR merged thanks.
