### ISSUE TITLE
Wrong labelling order inside the hgroup

### ISSUE THREAD

**Issue by GioZanga** [grame-cncm/faustide#52]
The labelling order of the sliders inside the hgroup it's wrong. I wrote a little piece of code in wich a set of sliders control the amplitude of a set of oscillators. The sliders are ordered in a strange way, they should be ordered like this: amp 1, amp 2 amp 3....... amp 15, amp 16. Instead they are ordered like this: amp 1, amp 10, amp 11 .......... amp 16, amp 2, amp 3.......... I'm using Google Chrome and my operating system it's Windows 10. Here's the code I wrote:

`import("stdfaust.lib");

freq = hslider("freq[unit:hz][scale:log]", 440, 1, 20000, 0.01) : si.smoo;

gain = hslider("gain", 1, 0, 1, 0.01) : si.smoo;

nPartials = 16;

amp(c) = vslider("amp %c", 0, 0, 1, 0.01) : si.smoo;

amplitude(c) = hgroup("amplitude", amp(c));

process = par(i, nPartials, os.osc(freq*(i+1)) * amplitude(i+1)) :> /(nPartials)* gain;`

**Comment by orlarey** [comment]
You can solve the problem by writing "amp %2c"

**Comment by sletz** [comment]
Faust just received a price for its good documentation ((-;, see: https://www.ouvrirlascience.fr/remise-des-prix-science-ouverte-du-logiciel-libre-de-la-recherche/

So of course this specific thing is explained, see: https://faustdoc.grame.fr/manual/syntax/#variable-parts-of-a-label

**Comment by GioZanga** [comment]
Thanks, Sorry I'm new to Faust

Il sab 5 feb 2022, 21:52 Stéphane Letz ***@***.***> ha
scritto:
