### ISSUE TITLE
Polyphonic MIDI "effect" Function

### ISSUE THREAD

**Issue by Pack-Blepper** [grame-cncm/faustide#84]
Beginning with this example:
```
declare options "[midi:on][nvoices:12]";
import("stdfaust.lib");
freq = hslider("freq",200,50,1000,0.01);
gain = hslider("gain",0.5,0,1,0.01);
gate = button("gate");
envelope = en.adsr(0.01,0.01,0.8,0.1,gate)*gain;
process = os.sawtooth(freq)*envelope <: _,_;
effect = dm.zita_light;
```
`zita_light` is a stereo reverberator -- it has two inputs and two outputs, which is why the signal is split at the end of `process`. It could also have been written like:

`process = os.sawtooth(freq)*envelope;`
`effect = _ <: dm.zita_light;`

But this now discards the right channel, as though `zita_light` only had one output. Whatever reverberator you put into `effect`, the compiler will attempt to send each input channel to the corresponding channel of the output while ignoring any `<:` and `:>` compositions. This:

`process = os.sawtooth(freq)*envelope;`
`effect = _ <: dm.zita_light <: _,_;`

still only outputs to the left channel, and this:

`process = os.sawtooth(freq)*envelope;`
`effect = dm.zita_light;`

causes the compiler to silently ignore `effect`, when it should give a sequential composition error.

**Comment by sletz** [comment]
@Fr0stbyteR stage bug since the same code works correctly in faustwasm standalone mode. Any idea ?

**Comment by Fr0stbyteR** [comment]
Something related to the auto-adaptation code for effects?
```
adapt(1,1) = _; adapt(2,2) = _,_; adapt(1,2) = _ <: _,_; adapt(2,1) = _,_ :> _;
adaptor(F,G) = adapt(outputs(F),inputs(G));
dsp_code = environment{${dspCode}};
process = adaptor(dsp_code.process, dsp_code.effect) : dsp_code.effect;
```

**Comment by sletz** [comment]
This adaptation code is inside faustwasm project right ?

**Comment by Fr0stbyteR** [comment]
> This adaptation code is inside faustwasm project right ?

Yes, the behavior should be consistent between faustwasm/Faust IDE.

**Comment by sletz** [comment]
So why does the problem occur in Faust IDE ?

**Comment by Fr0stbyteR** [comment]
I'm not quite sure if the problem is the adapter itself or there is another problem. Basically it means that the adapter works. And I cannot reproduce the last problem.
